version: '2'

services:
  nginx:
    image: nginx:1.10.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx_prod/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - djangoapp
    networks:
      - nginx_network
