version: '2'

services:
  nginx:
    image: nginx:1.10.3
    ports:
      - 8000:8000
    volumes:
      - ./config/nginx_test/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network
